spin_manifest_version = 2

[application]
authors = ["itowlson <ivan.towlson@fermyon.com>"]
description = ""
name = "cenote-ai"
version = "0.1.0"

[variables]
notion_db_id = { required = true, secret = true }
notion_api_key = { required = true, secret = true }

[[trigger.http]]
route = "/meeting-created"
component = "on-meeting-created"

[component.on-meeting-created]
source = "on-meeting-created/target/wasm32-wasip1/release/on_meeting_created.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.on-meeting-created.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "on-meeting-created"
watch = ["src/**/*.rs", "Cargo.toml"]

[[trigger.http]]
route = "/on-cron"
component = "on-cron"

[component.on-cron]
source = "on-cron/target/wasm32-wasip1/release/on_cron.wasm"
allowed_outbound_hosts = ["https://api.notion.com"]
key_value_stores = ["default"]
[component.on-cron.variables]
notion_db_id = "{{ notion_db_id }}"
notion_api_key = "{{ notion_api_key }}"
[component.on-cron.build]
command = "cargo build --target wasm32-wasip1 --release"
workdir = "on-cron"
watch = ["src/**/*.rs", "Cargo.toml"]
